version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "2020:2020"
    env_file:
      - env/common.env
    environment:
      GATEWAY_PORT: 2020
  eureka-service:
    build: ./eureka-service
    environment:
      EUREKA_PORT: 8761
  order-service:
    build: ./order-service
    env_file:
      - env/order.env
      - env/order_secret.env
      - env/common.env
    depends_on:
      - order-db
  order-db:
    image: postgres:12.1-alpine
    env_file:
      - env/order_secret.env
    volumes:
      - /var/lib/order-db:/var/lib/postgresql/data
  payment-service:
    build: ./payment-service
    env_file:
      - env/payment.env
      - env/payment_secret.env
      - env/common.env
    depends_on:
      - payment-db
  payment-db:
    image: postgres:12.1-alpine
    env_file:
      - env/payment_secret.env
    volumes:
      - /var/lib/payment-db:/var/lib/postgresql/data
  storehouse-service:
    build: ./storehouse-service
    env_file:
      - env/storehouse.env
      - env/storehouse_secret.env
      - env/common.env
    depends_on:
      - storehouse-db
  storehouse-db:
    image: postgres:12.1-alpine
    env_file:
      - env/storehouse_secret.env
    volumes:
      - /var/lib/storehouse-db:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"