spring:
  application:
    name: api-gateway

server:
  port: ${GATEWAY_PORT}
zuul:
  routes:
    eureka:
      path: "/eureka/**"
      url: "http://eureka-service:8761"
    storehouse-service:
      path: "/api/warehouse/**"
      serviceId: "storehouse-service"
      stripPrefix: false
    order-service:
      path: "/api/orders/**"
      serviceId: "order-service"
      stripPrefix: false
    payment-service:
      path: "/api/payment/**"
      serviceId: "payment-service"
      stripPrefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

turbine:
  appConfig: storehouse-service,order-service,payment-service,api-gateway
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  instanceUrlSuffix:
    default: actuator/hystrix.stream

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    healthcheck:
      enabled: true
    lease:
      duration: 5
