spring:
  application:
    name: order-service
  datasource:
    platform: postgres
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: rabbitmq
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

feign:
  hystrix:
    enabled: true
  client:
    config:
      storehouse-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    healthcheck:
      enabled: true
